export enum LogOut {
  USER_LOGOUT = 'USER_LOGOUT',
  DEVICE_LOGOUT = 'DEVICE_LOGOUT',
  ALL_DEVICES_LOGOUT = 'ALL_DEVICES_LOGOUT',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_LIMIT_EXCEEDED = 'TOKEN_LIMIT_EXCEEDED',
}

export enum VerifyCodeType {
 EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
 PASSWORD_RESET = "PASSWORD_RESET",  
}